# This is a basic workflow to help you get started with Actions

name: CI
env:
  CI: false
# Controls when the action will run.
on:
  push:
    branches-ignore: [master]
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: Use Node v12 ☋
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Install packages
        run: npm install
      - name: Build 🔧
        run: npm run build
